class SoottyError(Exception):
    """Raised on any user-facing error in this module."""

    pass


class SoottyInternalError(Exception):
    """Raised on any Sootty internal failure."""

    pass
